Add a new example

diff --git a/trc b/trc
--- a/trc
+++ b/trc
@@ -21,23 +21,29 @@ trc_version="v1.1.3"
 
 set +e # Do not exit on errors by default
 if [[ "${RC_DEBUG}" = "true" ]]; then
-    set -x # Turns on Debug mode if true
+    set -x # Turns on Debug mode
 fi
 
 main() {
+    # If it's needed to have extra paths, update $PATH at `boot` stage
+    PATH="/sbin:/bin:/usr/sbin:/usr/bin"
+    
     check_ver_usage "$1"
+    check_req_bins ls ps pkill sleep date basename dirname
 
+    # It's possible to exit from the last `halt` command with ${_exit_status} which comes from main() 
+    # and rewrite by this an exit status of the `halt` stage which always has a priority against main's exit status
     trap '_exit_status=$?; trap '_ignore_mt_ex=1' EXIT; debug "exit-trap (exitcode=${_exit_status})"; hook_main_exit' EXIT
     trap '_es_mt_s=$?; trap '_ignore_mt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=${_es_mt_s})"; exit ${_es_mt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
     trap '_es_mt_er=$?; trap '_ignore_mt_er=1' ERR; if [[ "${RC_WAIT_POLICY}" = "wait_err" ]]; then debug "err-trap (exitcode=${_es_mt_er})"; exit ${_es_mt_er}; fi' ERR
 
     local _wait_bg_cmd _file _es_m_f=0 _es_m_d=0
 
-    export SELF_NAME=$(basename $0 .sh) # Self name for logging purpose
+    export SELF_NAME=$(run -p basename $0 .sh) # Self name for logging purpose
     export MAINPID="${BASHPID}" # PID of the main process
     : ${RC_WAIT_POLICY:=wait_any}; export RC_WAIT_POLICY 
 
-    dir_name=$(dirname $0)
+    dir_name=$(run -p dirname $0)
     boot_stage_left=0
     halt_cmds_exist=0
     halt_cmds=()
@@ -45,9 +51,9 @@ main() {
     ns="main" # Name Space
 
     case "${RC_WAIT_POLICY}" in
-        wait_all)  _wait_bg_cmd="builtin command wait";;
-        wait_any)  _wait_bg_cmd="builtin command wait";;
-        wait_err)  _wait_bg_cmd="builtin command wait";;
+        wait_all)  _wait_bg_cmd="run wait";;
+        wait_any)  _wait_bg_cmd="run wait";;
+        wait_err)  _wait_bg_cmd="run wait";;
         *)         _wait_bg_cmd=":";;
     esac
 
@@ -62,25 +68,27 @@ main() {
     debug "Looking for \`boot\` scripts and commands..."
     {
         # Reads commands from files to run before everything
-        set -e # On errors exits regardless of RC_WAIT_POLICY
-        for _file in $(ls ${dir_name}/trc.boot.* ${dir_name}/trc.d/boot.* 2>/dev/null || true); do
+        for _file in $(run -p ls ${dir_name}/trc.boot.* ${dir_name}/trc.d/boot.* 2>/dev/null || true); do
             log "Launching on the $(ns_long ${ns}): ${_file}"
+            set -e 
             . ${_file}
+            set +e
         done
 
-        # Checks for boot tasks in the command line
+        # Checks for boot tasks in the command line (all commands and their parameters should be supplied as one parameter)
         while [[ "$1" = "-B" ]]; do
             shift
             log "Launching on the $(ns_long ${ns}): $1"
+            set -e 
             eval "$1"
+            set +e
             shift
         done
-        set +e
     }
     boot_stage_left=1
 
     debug "Looking for \`halt\` commands..."
-    # Collects commands for the `halt` stage from a command line
+    # Collects commands for the `halt` stage from a command line to be run on exit from the main exit trap
     while [[ "$1" = "-H" ]]; do
         shift
             halt_cmds_exist=1
@@ -90,7 +98,7 @@ main() {
 
     debug "Looking for \`async\` scripts and commands..."
     # Reads commands from files to run on the background (in parallel)
-    for _file in $(ls ${dir_name}/trc.bg.* ${dir_name}/trc.async.* ${dir_name}/trc.d/async.* 2>/dev/null || true); do
+    for _file in $(run -p ls ${dir_name}/trc.bg.* ${dir_name}/trc.async.* ${dir_name}/trc.d/async.* 2>/dev/null || true); do
         { # supressing stderr for avoiding uncontrolled messages like "Terminated" or "Killed"
               (
                 # Run this on any exit, catching the exitcode of the "main" command,
@@ -110,7 +118,7 @@ main() {
         child_pids="${child_pids} $!"
     done
 
-    # Checks for background tasks in the command line
+    # Checks for background tasks in the command line (all commands and their parameters should be supplied as one parameter)
     while [[ "$1" = "-D" ]]; do
         shift
         { # supressing stderr for avoiding uncontrolled messages like "Terminated" or "Killed"
@@ -130,7 +138,7 @@ main() {
 
     debug "Looking for \`sync\` scripts and commands..." 
     # Checks for foreground tasks in files (sequentially)
-    for _file in $(ls ${dir_name}/trc.fg.* ${dir_name}/trc.sync.* ${dir_name}/trc.d/sync.* 2>/dev/null || true); do
+    for _file in $(run -p ls ${dir_name}/trc.fg.* ${dir_name}/trc.sync.* ${dir_name}/trc.d/sync.* 2>/dev/null || true); do
         (
             trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "${_file}"' EXIT
             trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
@@ -144,7 +152,7 @@ main() {
         _es_m_f=$?
     done
 
-    # Checks for foreground tasks in the command line
+    # Checks for foreground tasks in the command line (all commands and their parameters should be supplied as one parameter)
     while [[ "$1" = "-F" ]]; do
         shift
         (
@@ -160,7 +168,7 @@ main() {
         shift
     done
 
-    # Checks for a foreground task in the command line (one parameter with all commands)
+    # Checks for a foreground task in the command line (without any quotation!)
     if [[ -n "$*" ]]; then
         (
             set -e
@@ -194,12 +202,12 @@ main() {
 
 say() {
     if [[ "${RC_VERBOSE}" = "true" ]]; then
-        echo "$@"
+        run echo "$@"
     fi
 }
 
 log() {
-    say "$(date '+%Y-%m-%d %H:%M:%S') ${SELF_NAME} [${ns}/${BASHPID}]: $@"
+    say "$(run -p date '+%Y-%m-%d %H:%M:%S') ${SELF_NAME} [${ns}/${BASHPID}]: $@"
 }
 
 warn() {
@@ -220,34 +228,38 @@ debug() {
 hook_main_exit() {
     local _pid _cpids _file _cmd _es_mtt_h=0 _term_timeout=5
 
+    # If it fails in the `boot` stage, it appears here with 'set -e'. So, reset to +e again
+    set +e
     log "Trying to terminate sub-processes..."
     for _pid in ${child_pids}; do
-        if ps -p ${_pid} &> /dev/null; then
-            debug "terminating the child process <pid=${_pid}>"
+        if run -p ps -p ${_pid} &> /dev/null; then
+            log "terminating the child process <pid=${_pid}>"
 
             # Removes all unexpected sub-processes
-            _cpids="$(pgrep -P ${_pid} -d,)"
-            kill -TERM ${_pid} $(echo "${_cpids}" | tr ',' ' ') &> /dev/null
+            _cpids="$(run -p pgrep -P ${_pid} -d,)"
+            run kill -TERM ${_pid} $(echo "${_cpids}" | tr ',' ' ') &> /dev/null
 
-            while ps -p ${_pid},${_cpids} &> /dev/null && [[ ${_term_timeout} -gt 0 ]]
+            while run -p ps -p ${_pid},${_cpids} &> /dev/null && [[ ${_term_timeout} -gt 0 ]]
             do
-                sleep 1
+                run -p sleep 1
                 : $((_term_timeout--))
             done
 
-            if ps -p ${_pid},${_cpids} &>/dev/null; then
-                kill -KILL ${_pid} $(echo "${_cpids}" | tr ',' ' ') &> /dev/null
+            if run -p ps -p ${_pid},${_cpids} &>/dev/null; then
+                run kill -KILL ${_pid} $(run echo "${_cpids}" | run -p tr ',' ' ') &> /dev/null
             fi
         fi
     done
-    # Removes all unexpected sub-processes
-    pkill -KILL -P ${MAINPID} &> /dev/null || true
+    debug "removing all unexpected sub-processes"
+    if ! run -p pkill -KILL -P ${MAINPID} &> /dev/null; then
+        true
+    fi
 
     # --- `halt`
     if [[ boot_stage_left -eq 1 ]]; then
         debug "Looking for \`halt\` scripts..."
         # Checks for shutdown tasks in files (sequentially)
-        for _file in $(ls ${dir_name}/trc.sd.* ${dir_name}/trc.halt.* ${dir_name}/trc.d/halt.* 2>/dev/null || true); do
+        for _file in $(run -p ls ${dir_name}/trc.sd.* ${dir_name}/trc.halt.* ${dir_name}/trc.d/halt.* 2>/dev/null || true); do
             halt_cmds_exist=1
             (
                 set -e # Exit on errors in the sub-shell
@@ -292,9 +304,9 @@ hook_sub_exit() {
 
     if [[ "${RC_WAIT_POLICY}" = "wait_any" ]]; then 
         # If exiting from a bg process and don't need to wait other processes, let's stop the main
-        if ps -p ${MAINPID} &> /dev/null; then
+        if run -p ps -p ${MAINPID} &> /dev/null; then
             debug "terminating the main process <pid=${MAINPID}>"
-            kill -TERM ${MAINPID} &> /dev/null
+            run kill -TERM ${MAINPID} &> /dev/null
         fi
     fi
 
@@ -304,7 +316,7 @@ hook_sub_exit() {
 infinite_loop() {
     log "Activated infinite loop! To stop, press <Ctrl+C> or send SIGTERM..."
     while true; do
-        sleep 60
+        run -p sleep 1
     done
 }
 
@@ -332,18 +344,30 @@ check_ver_usage() {
 
 print_usage() {
     local _self=$0
-    echo "Usage: ${_self} [-w|--workdir 'dir'] [-B 'cmds' [...]] [-H 'cmds' [...]] [-D 'cmds' [...]] [-F 'cmds' [...]] [cmd [args]]"
-    echo "Examples:"
-    echo -e " $ ${_self} -B 'name=\$(id -un); echo booting...' -H 'echo halting...' -F 'echo Hello, \${name}!'"
-    echo -e " $ RC_WAIT_POLICY=wait_all ${_self} -D 'echo Hello' -D 'sleep 2; echo World' echo waiting..."
-    echo -e " $ RC_VERBOSE=true ${_self} -F 'echo -n \"Hello \"; echo World'"
-    echo -e " $ ${_self} --workdir /opt/app"
+    run echo "Usage: ${_self} [-w|--workdir 'dir'] [-B 'cmds' [...]] [-H 'cmds' [...]] [-D 'cmds' [...]] [-F 'cmds' [...]] [cmd [args]]"
+    run echo "Examples:"
+    run echo -e " $ ${_self} -B 'name=\$(id -un); echo booting...' -H 'echo halting...' -F 'echo Hello, \${name}!'"
+    run echo -e " $ RC_WAIT_POLICY=wait_all ${_self} -D 'echo Hello' -D 'sleep 2; echo World' echo waiting..."
+    run echo -e " $ RC_VERBOSE=true ${_self} -F 'echo -n \"Hello \"; echo World'"
+    run echo -e " $ ${_self} --workdir /opt/app"
     exit 0
 }
 
 print_version() {
-    echo "$trc_version"
+    run echo "$trc_version"
     exit 0
+}
+
+run() {
+    builtin command "$@"
+}
+
+check_req_bins() {
+    local _cmd
+
+    for _cmd in "$@"; do
+        run -v ${_cmd} &> /dev/null || { echo "There is no the required command: ${_cmd}" >&2; exit 1; }
+    done
 }
 
 main "$@"
