Fix output

diff --git a/trc b/trc
--- a/trc
+++ b/trc
@@ -29,9 +29,16 @@ main() {
     export SELF_NAME=$(basename $0 .sh) # Self name for logging purpose
     export DIR_NAME=$(dirname $0)
     export MAINPID="$BASHPID" # PID of the main process
+    export EXIT_FLAG="/tmp/trc.$MAINPID.exiting"
     childpid="" # Collecting child processes
     ns="main" # Name Space
     local _wait_bg_cmd _file _exitcode=0 _exitcode2=0
+
+    # Checks if there is an exit flag on startup
+    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
+        warn "An exit flag ${EXIT_FLAG} exists! Exiting..."
+        exit 1
+    fi
 
     case "$RC_WAIT_POLICY" in
         wait_all)  _wait_bg_cmd="command -p wait";;
@@ -46,7 +53,6 @@ main() {
     for _file in $(ls $DIR_NAME/trc.boot.* $DIR_NAME/trc.d/boot.* 2>/dev/null || true); do
         set -e
 
-        ns="boot"
         say "Running on the $(ns_long $ns): $_file"
         . $_file
 
@@ -58,7 +64,6 @@ main() {
         shift
         set -e
 
-        ns="boot"
         say "Running on the $(ns_long $ns): $1"
         eval "$1"
 
@@ -92,7 +97,7 @@ main() {
         (
             # Run this on any exit, catching the exitcode of the "main" command,
             # printing additional info and finishing up this sub-program with the right exitcode
-            trap '_exitcode=$?; hook_sub_exit $_exitcode "$@"; say "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
+            trap '_exitcode=$?; hook_sub_exit $_exitcode "$1"; say "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
 
             # In case of exit on errors (set -e), catch exitcode and exit with it, which
             # will lead to triggering an EXIT trap
@@ -179,6 +184,9 @@ warn() {
 hook_main_exit() {
     local _pid _file
 
+    # Creating an exit flag
+    touch ${EXIT_FLAG} || warn "Cannot create ${EXIT_FLAG}"
+
     say "Going down. Running shutdown scripts..."
     # Checks for shutdown tasks in files (sequentially)
     for _file in $(ls $DIR_NAME/trc.sd.* $DIR_NAME/trc.halt.* $DIR_NAME/trc.d/halt.* 2>/dev/null || true); do
@@ -211,6 +219,11 @@ hook_main_exit() {
     done
     # Removes all unexpected sub-processes
     pkill -KILL -P $MAINPID &> /dev/null
+
+    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
+        rm -f ${EXIT_FLAG} || warn "Cannot remove ${EXIT_FLAG}"
+    fi
+
     say "Exited."
 
     # It's not needed to exit with a proper exit code here.
@@ -225,12 +238,13 @@ hook_sub_exit() {
 
     say "Exiting on the $(ns_long $ns) ($_rc): $@"
 
-    if [ "$RC_WAIT_POLICY" = "wait_any" ]
-    then
-        # If exiting from a bg process and don't need to wait other processes, let's stop the main
-        if ps -p $MAINPID &> /dev/null; then
-            warn " - terminating main <$MAINPID>"
-            kill -TERM $MAINPID &> /dev/null
+    if [[ "$RC_WAIT_POLICY" = "wait_any" ]]; then 
+        if [[ -n "${EXIT_FLAG}" ]] && [[ ! -f ${EXIT_FLAG} ]]; then
+            # If exiting from a bg process and don't need to wait other processes, let's stop the main
+            if ps -p $MAINPID &> /dev/null; then
+                warn " - terminating main <$MAINPID>"
+                kill -TERM $MAINPID &> /dev/null
+            fi
         fi
     fi
     # To prevent invoking error trap from error trap ;)
