Add more examples

diff --git a/trc b/trc
--- a/trc
+++ b/trc
@@ -4,11 +4,13 @@
 # Copyright (c) 2016,2017 by Oleksii Tsvietnov, me@vorakl.name
 # Version: 1.1.0
 
-# --[ Environment ]--
+# --[ Environment variables ]--
 # RC_DEBUG (true|false) [false]
 #    Prints out all commands which are being executed
 # RC_VERBOSE (true|false) [false]
 #    Prints out service information
+# RC_VERBOSE_EXTRA (true|false) [false]
+#    Prints out additional service information
 # RC_WAIT_POLICY (wait_all|wait_any|wait_forever) [wait_any]
 #    - wait_all      quit after exiting the last command (back- or foreground)
 #    - wait_any      quit after exiting any of command (including zero commands)
@@ -16,20 +18,20 @@
 #                    Usefull in case of daemons which are detaching and exiting
 
 set +e # Do not exit on errors by default
-if [[ "$RC_DEBUG" = "true" ]]; then
+if [[ "${RC_DEBUG}" = "true" ]]; then
     set -x # Turns on Debug mode if true
 fi
 : ${RC_WAIT_POLICY:=wait_any} # Sets default value for a wait policy
 
 main() {
-    trap '_exitcode=$?; hook_main_exit; debug "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
-    trap '_exitcode=$?; debug "sig-trap ($_exitcode)"; exit $_exitcode' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-    trap '_exitcode=$?; debug "err-trap ($_exitcode)"; exit $_exitcode' ERR
+    trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_main_exit; exit ${_exitcode}' EXIT
+    trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+    trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
 
     export SELF_NAME=$(basename $0 .sh) # Self name for logging purpose
     export DIR_NAME=$(dirname $0)
-    export MAINPID="$BASHPID" # PID of the main process
-    export EXIT_FLAG="/tmp/trc.$MAINPID.exiting"
+    export MAINPID="${BASHPID}" # PID of the main process
+    export EXIT_FLAG="/tmp/trc.${MAINPID}.exiting"
     childpid="" # Collecting child processes
     ns="main" # Name Space
     local _wait_bg_cmd _file _exitcode=0 _exitcode2=0
@@ -39,21 +41,21 @@ main() {
         err "An exit flag ${EXIT_FLAG} exists! Exiting..."
     fi
 
-    case "$RC_WAIT_POLICY" in
+    case "${RC_WAIT_POLICY}" in
         wait_all)  _wait_bg_cmd="command -p wait";;
         wait_any)  _wait_bg_cmd="command -p wait";;
         *)         _wait_bg_cmd=":";;
     esac
 
-    log "The wait policy: $RC_WAIT_POLICY"
+    log "The wait policy: ${RC_WAIT_POLICY}"
 
 
     # Reads commands from files to run before everything
-    for _file in $(ls $DIR_NAME/trc.boot.* $DIR_NAME/trc.d/boot.* 2>/dev/null || true); do
+    for _file in $(ls ${DIR_NAME}/trc.boot.* ${DIR_NAME}/trc.d/boot.* 2>/dev/null || true); do
         set -e
 
-        log "Launching on the $(ns_long $ns): $_file"
-        . $_file
+        log "Launching on the $(ns_long ${ns}): ${_file}"
+        . ${_file}
 
         set +e
     done
@@ -63,7 +65,7 @@ main() {
         shift
         set -e
 
-        log "Launching on the $(ns_long $ns): $1"
+        log "Launching on the $(ns_long ${ns}): $1"
         eval "$1"
 
         set +e
@@ -71,22 +73,22 @@ main() {
     done
 
     # Reads commands from files to run on the background (in parallel)
-    for _file in $(ls $DIR_NAME/trc.bg.* $DIR_NAME/trc.async.* $DIR_NAME/trc.d/async.* 2>/dev/null || true); do
+    for _file in $(ls ${DIR_NAME}/trc.bg.* ${DIR_NAME}/trc.async.* ${DIR_NAME}/trc.d/async.* 2>/dev/null || true); do
          {
           (
             set -e
             # Run this on any exit, catching the exitcode of the "main" command,
             # printing additional info and finishing up this sub-program with the right exitcode
-            trap '_exitcode=$?; hook_sub_exit $_exitcode "$_file"; debug "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
+            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "${_file}"; exit ${_exitcode}' EXIT
 
             # In case of exit on errors (set -e) or by a signal, catch exitcode and exit with it, which
             # will lead to triggering an EXIT trap
-            trap '_exitcode=$?; debug "sig-trap ($_exitcode)"; exit $_exitcode' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap ($_exitcode)"; exit $_exitcode' ERR
+            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
 
             ns="async"
-            log "Launching on the $(ns_long $ns): $_file"
-            . $_file
+            log "Launching on the $(ns_long ${ns}): ${_file}"
+            . ${_file}
           )& 
          } 2> /dev/null
 
@@ -99,12 +101,12 @@ main() {
         { # supressing stderr for avoiding uncontrolled messages like "Terminated" or "Killed"
           (
             set -e
-            trap '_exitcode=$?; hook_sub_exit $_exitcode "$1"; debug "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
-            trap '_exitcode=$?; debug "sig-trap ($_exitcode)"; exit $_exitcode' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap ($_exitcode)"; exit $_exitcode' ERR
+            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$1"; exit ${_exitcode}' EXIT
+            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
 
             ns="async"
-            log "Launching on the $(ns_long $ns): $1"
+            log "Launching on the $(ns_long ${ns}): $1"
             eval "$1"
           )& 
         } 2> /dev/null
@@ -112,49 +114,49 @@ main() {
         shift
     done
 
+   # Checks for foreground tasks in files (sequentially)
+    for _file in $(ls ${DIR_NAME}/trc.fg.* ${DIR_NAME}/trc.sync.* ${DIR_NAME}/trc.d/sync.* 2>/dev/null || true); do
+        (
+            set -e
+            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "${_file}"; exit ${_exitcode}' EXIT
+            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+
+            ns="sync"
+            log "Launching on the $(ns_long ${ns}): ${_file}"
+            . ${_file}
+        )
+        # Catch the exitcode of a foreground sub-program
+        _exitcode=$?
+    done
+
     # Checks for foreground tasks in the command line
     while [[ "$1" = "-F" ]]; do
         shift
         (
             set -e
-            trap '_exitcode=$?; hook_sub_exit $_exitcode "$1"; debug "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
-            trap '_exitcode=$?; debug "sig-trap ($_exitcode)"; exit $_exitcode' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap ($_exitcode)"; exit $_exitcode' ERR
+            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$1"; exit ${_exitcode}' EXIT
+            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
 
             ns="sync"
-            log "Launching on the $(ns_long $ns): $1"
+            log "Launching on the $(ns_long ${ns}): $1"
             eval "$1"
         )
         shift
         _exitcode=$?
     done
 
-    # Checks for foreground tasks in files (sequentially)
-    for _file in $(ls $DIR_NAME/trc.fg.* $DIR_NAME/trc.sync.* $DIR_NAME/trc.d/sync.* 2>/dev/null || true); do
-        (
-            set -e
-            trap '_exitcode=$?; hook_sub_exit $_exitcode "$_file"; debug "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
-            trap '_exitcode=$?; debug "sig-trap ($_exitcode)"; exit $_exitcode' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap ($_exitcode)"; exit $_exitcode' ERR
-
-            ns="sync"
-            log "Launching on the $(ns_long $ns): $_file"
-            . $_file
-        )
-        # Catch the exitcode of a foreground sub-program
-        _exitcode=$?
-    done
-
-    # Checks for a foreground task in the command line (one parameter with all commands)
+     # Checks for a foreground task in the command line (one parameter with all commands)
     if [[ -n "$*" ]]; then
         (
             set -e
-            trap '_exitcode=$?; hook_sub_exit $_exitcode "$@"; debug "exit-trap ($_exitcode)"; exit $_exitcode' EXIT
-            trap '_exitcode=$?; debug "sig-trap ($_exitcode)"; exit $_exitcode' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap ($_exitcode)"; exit $_exitcode' ERR
+            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$@"; exit ${_exitcode}' EXIT
+            trap '_exitcode=$?; debug "sig-trap (exitcode=$_exitcode)"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_exitcode=$?; debug "err-trap (exitcode=$_exitcode)"; exit ${_exitcode}' ERR
 
             ns="sync"
-            log "Launching on the $(ns_long $ns): $@"
+            log "Launching on the $(ns_long ${ns}): $@"
             "$@"
         )
         # Catch the exitcode of a foreground sub-program
@@ -163,28 +165,28 @@ main() {
 
     # Wait for all background processes and exit with a status of the last one
     # or with 128+SIGNAL in case of getting a signal
-    $_wait_bg_cmd $childpid
+    ${_wait_bg_cmd} ${childpid}
     _exitcode2=$?
 
-    if [ $_exitcode2 -ne 0 ]; then
-        _exitcode=$_exitcode2 # update exit code only if one of background processes has failed
+    if [ ${_exitcode2} -ne 0 ]; then
+        _exitcode=${_exitcode2} # update exit code only if one of background processes has failed
     fi
 
-    if [[ "$RC_WAIT_POLICY" = "wait_forever" ]]; then
+    if [[ "${RC_WAIT_POLICY}" = "wait_forever" ]]; then
         infinite_loop
     fi
 
-    return $_exitcode
+    return ${_exitcode}
 }
 
 say() {
-    if [[ "$RC_VERBOSE" = "true" ]]; then
-        echo -e "$@"
+    if [[ "${RC_VERBOSE}" = "true" ]]; then
+        echo "$@"
     fi
 }
 
 log() {
-    say "$(date '+%Y-%m-%d %H:%M:%S') ${SELF_NAME} [$ns/$BASHPID]: $@"
+    say "$(date '+%Y-%m-%d %H:%M:%S') ${SELF_NAME} [${ns}/${BASHPID}]: $@"
 }
 
 warn() {
@@ -197,8 +199,8 @@ err() {
 }
 
 debug() {
-    if [[ "$RC_DEBUG" = "true" ]]; then
-        log "$@"
+    if [[ "${RC_VERBOSE_EXTRA}" = "true" ]]; then
+        log " - $@"
     fi
 }
 
@@ -214,43 +216,42 @@ hook_main_exit() {
     # Creating an exit flag
     touch ${EXIT_FLAG} || warn "Cannot create ${EXIT_FLAG}"
 
-    local _pid _file
+    local _pid _file _term_timeout=5
 
     log "Going down. Running shutdown scripts..."
     # Checks for shutdown tasks in files (sequentially)
-    for _file in $(ls $DIR_NAME/trc.sd.* $DIR_NAME/trc.halt.* $DIR_NAME/trc.d/halt.* 2>/dev/null || true); do
+    for _file in $(ls ${DIR_NAME}/trc.sd.* ${DIR_NAME}/trc.halt.* ${DIR_NAME}/trc.d/halt.* 2>/dev/null || true); do
         (
             ns="halt"
             set -e # Exit on errors in the sub-shell
-            log "Running the shutdown script: $_file"
-            . $_file
+            log "Running the shutdown script: ${_file}"
+            . ${_file}
         )
     done
 
     log "Handling of termination..."
-    for _pid in $childpid; do
-        if ps -p $_pid &> /dev/null; then
-            log " - terminating the child <$_pid>"
+    for _pid in ${childpid}; do
+        if ps -p ${_pid} &> /dev/null; then
+            debug "terminating the child process <pid=${_pid}>"
 
             # Removes all unexpected sub-processes
-            pkill -TERM -P $_pid &> /dev/null           
-            term_timeout=5
-            kill -TERM $_pid &> /dev/null
+            pkill -TERM -P ${_pid} &> /dev/null           
+            kill -TERM ${_pid} &> /dev/null
 
-            while ps -p $_pid &>/dev/null && [[ ${term_timeout} -gt 0 ]]
+            while ps -p ${_pid} &>/dev/null && [[ ${_term_timeout} -gt 0 ]]
             do
                 sleep 1
-                : $((term_timeout--))
+                : $((_term_timeout--))
             done
 
-            if  ps -p $_pid &>/dev/null; then
-                pkill -KILL -P $_pid &> /dev/null
-                kill -KILL $_pid &> /dev/null
+            if  ps -p ${_pid} &>/dev/null; then
+                pkill -KILL -P ${_pid} &> /dev/null
+                kill -KILL ${_pid} &> /dev/null
             fi
         fi
     done
     # Removes all unexpected sub-processes
-    pkill -KILL -P $MAINPID &> /dev/null
+    pkill -KILL -P ${MAINPID} &> /dev/null
 
     if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
         rm -f ${EXIT_FLAG} || warn "Cannot remove ${EXIT_FLAG}"
@@ -268,14 +269,14 @@ hook_sub_exit() {
     local _rc=$1 # Getting the exit code for a logging purpose only
     shift
 
-    log "Exiting on the $(ns_long $ns) ($_rc): $@"
+    log "Exiting on the $(ns_long ${ns}) (exitcode=${_rc}): $@"
 
-    if [[ "$RC_WAIT_POLICY" = "wait_any" ]]; then 
+    if [[ "${RC_WAIT_POLICY}" = "wait_any" ]]; then 
         if [[ -n "${EXIT_FLAG}" ]] && [[ ! -f ${EXIT_FLAG} ]]; then
             # If exiting from a bg process and don't need to wait other processes, let's stop the main
-            if ps -p $MAINPID &> /dev/null; then
-                log " - terminating the main <$MAINPID>"
-                kill -TERM $MAINPID &> /dev/null
+            if ps -p ${MAINPID} &> /dev/null; then
+                debug "terminating the main process <pid=${MAINPID}>"
+                kill -TERM ${MAINPID} &> /dev/null
             fi
         fi
     fi
@@ -302,7 +303,7 @@ ns_long() {
          *)       _ns="$1";;
     esac
 
-    echo "$_ns"
+    echo "${_ns}"
 }
 
 main "$@"
