Fixed multiply traps invoking

diff --git a/trc b/trc
--- a/trc
+++ b/trc
@@ -20,36 +20,34 @@ trc_version="1.1.0"
 #    - wait_err      quits after the first failed command
 
 set +e # Do not exit on errors by default
-[[ "${RC_DEBUG}" = "true" ]] && set -x # Turns on Debug mode if true
+if [[ "${RC_DEBUG}" = "true" ]]; then
+    set -x # Turns on Debug mode if true
+fi
 
 main() {
     check_ver_usage $1
 
-    trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_main_exit || exit $?; exit ${_exitcode}' EXIT
-    trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-    trap '_exitcode=$?; [[ "${RC_WAIT_POLICY}" = "wait_err" ]] && { debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}; }' ERR
+    trap '_es_mt_ex=$?; trap '_ignore_mt_ex=1' EXIT; debug "exit-trap (exitcode=${_es_mt_ex})"; hook_main_exit ${_es_mt_ex}' EXIT
+    trap '_es_mt_s=$?; trap '_ignore_mt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=${_es_mt_s})"; exit ${_es_mt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+    trap '_es_mt_er=$?; trap '_ignore_mt_er=1' ERR; if [[ "${RC_WAIT_POLICY}" = "wait_err" ]]; then debug "err-trap (exitcode=${_es_mt_er})"; exit ${_es_mt_er}; fi' ERR
 
-    local _wait_bg_cmd _file _exitcode=0 _exitcode2=0
+    local _wait_bg_cmd _file _es_m_f=0 _es_m_d=0
 
     export SELF_NAME=$(basename $0 .sh) # Self name for logging purpose
     export DIR_NAME=$(dirname $0)
     export MAINPID="${BASHPID}" # PID of the main process
-    export EXIT_FLAG="/tmp/trc.${MAINPID}.exiting"
     : ${RC_WAIT_POLICY:=wait_any}; export RC_WAIT_POLICY 
 
+    boot_stage_left=0
+    halt_cmds_exist=0
     halt_cmds=()
     child_pids="" # Collects of child processes
     ns="main" # Name Space
 
-    # Checks if there is an exit flag on startup
-    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
-        err "An exit flag ${EXIT_FLAG} exists! Exiting..."
-    fi
-
     case "${RC_WAIT_POLICY}" in
-        wait_all)  _wait_bg_cmd="command -p wait";;
-        wait_any)  _wait_bg_cmd="command -p wait";;
-        wait_err)  _wait_bg_cmd="command -p wait";;
+        wait_all)  _wait_bg_cmd="builtin command wait";;
+        wait_any)  _wait_bg_cmd="builtin command wait";;
+        wait_err)  _wait_bg_cmd="builtin command wait";;
         *)         _wait_bg_cmd=":";;
     esac
 
@@ -67,19 +65,19 @@ main() {
         # Checks for boot tasks in the command line
         while [[ "$1" = "-B" ]]; do
             shift
-
             log "Launching on the $(ns_long ${ns}): $1"
             eval "$1"
-
             shift
         done
         set +e
     }
+    boot_stage_left=1
 
     debug "Looking for \`halt\` commands..."
     # Collects commands for the `halt` stage from a command line
     while [[ "$1" = "-H" ]]; do
         shift
+            halt_cmds_exist=1
             halt_cmds[${#halt_cmds[*]}]="$1"
         shift
     done
@@ -91,12 +89,12 @@ main() {
               (
                 # Run this on any exit, catching the exitcode of the "main" command,
                 # printing additional info and finishing up this sub-program with the right exitcode
-                trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "${_file}"; exit ${_exitcode}' EXIT
+                trap '_es_dt_ex=$?; trap '_ignore_mt_ex=1' EXIT; debug "exit-trap (exitcode=${_es_dt_ex})"; hook_sub_exit ${_es_dt_ex} "${_file}"' EXIT
 
                 # In case of exit on errors (set -e) or by a signal, catch exitcode and exit with it, which
                 # will lead to triggering an EXIT trap
-                trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-                trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+                trap '_es_dt_s=$?; trap '_ignore_dt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_dt_s)"; exit ${_es_dt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+                trap '_es_dt_er=$?; trap '_ignore_dt_er=1' ERR; debug "err-trap (exitcode=$_es_dt_er)"; exit ${_es_dt_er}' ERR
 
                 ns="async"
                 log "Launching on the $(ns_long ${ns}): ${_file}"
@@ -111,9 +109,9 @@ main() {
         shift
         { # supressing stderr for avoiding uncontrolled messages like "Terminated" or "Killed"
               (
-                trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$1"; exit ${_exitcode}' EXIT
-                trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-                trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+                trap '_es_dt_ex=$?; trap '_ignore_dt_ex=1' EXIT; debug "exit-trap (exitcode=${_es_dt_ex})"; hook_sub_exit ${_es_dt_ex} "$1"' EXIT
+                trap '_es_dt_s=$?; trap '_ignore_dt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_dt_s)"; exit ${_es_dt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+                trap '_es_dt_er=$?; trap '_ignore_dt_er=1' ERR; debug "err-trap (exitcode=$_es_dt_er)"; exit ${_es_dt_er}' ERR
 
                 ns="async"
                 log "Launching on the $(ns_long ${ns}): $1"
@@ -128,31 +126,31 @@ main() {
     # Checks for foreground tasks in files (sequentially)
     for _file in $(ls ${DIR_NAME}/trc.fg.* ${DIR_NAME}/trc.sync.* ${DIR_NAME}/trc.d/sync.* 2>/dev/null || true); do
         (
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "${_file}"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+            trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "${_file}"; exit ${_es_ft_ex}' EXIT
+            trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_es_ft_er=$?; trap '_ignore_ft_er=1' ERR; debug "err-trap (exitcode=$_es_ft_er)"; exit ${_es_ft_er}' ERR
 
             ns="sync"
             log "Launching on the $(ns_long ${ns}): ${_file}"
             . ${_file}
         )
         # Catch the exitcode of a foreground sub-program
-        _exitcode=$?
+        _es_m_f=$?
     done
 
     # Checks for foreground tasks in the command line
     while [[ "$1" = "-F" ]]; do
         shift
         (
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$1"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+            trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "$1"; exit ${_es_ft_ex}' EXIT
+            trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_es_ft_er=$?; trap '_ignore_ft_er=1' ERR; debug "err-trap (exitcode=$_es_ft_er)"; exit ${_es_ft_er}' ERR
 
             ns="sync"
             log "Launching on the $(ns_long ${ns}): $1"
             eval "$1"
         )
-        _exitcode=$?
+        _es_m_f=$?
         shift
     done
 
@@ -160,32 +158,32 @@ main() {
     if [[ -n "$*" ]]; then
         (
             set -e
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$@"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=$_exitcode)"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=$_exitcode)"; exit ${_exitcode}' ERR
+            trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "$@"; exit ${_es_ft_ex}' EXIT
+            trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_es_ft_er=$?; trap '_ignore_ft_er=1' ERR; debug "err-trap (exitcode=$_es_ft_er)"; exit ${_es_ft_er}' ERR
 
             ns="sync"
             log "Launching on the $(ns_long ${ns}): $@"
             "$@"
         )
         # Catch the exitcode of a foreground sub-program
-        _exitcode=$?
+        _es_m_f=$?
     fi
 
     # Wait for all background processes and exit with a status of the last one
     # or with 128+SIGNAL in case of getting a signal
-    ${_wait_bg_cmd} ${child_pids}
-    _exitcode2=$?
+    # this is a work around for not trigerring ERR trap in main() two times in case of non 0 exist status
+    ${_wait_bg_cmd} ${child_pids} || _es_m_d=$?
 
-    if [ ${_exitcode2} -ne 0 ]; then
-        _exitcode=${_exitcode2} # update exit code only if one of background processes has failed
+    if [ ${_es_m_d} -ne 0 ]; then
+        _es_m_f=${_es_m_d} # update exit code only if one of background processes has failed
     fi
 
     if [[ "${RC_WAIT_POLICY}" = "wait_forever" ]]; then
         infinite_loop
     fi
 
-    return ${_exitcode}
+    return ${_es_m_f}
 }
 
 say() {
@@ -214,16 +212,10 @@ debug() {
 }
 
 hook_main_exit() {
-    # Checks if there is an exit flag on exit
-    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
-        warn "The exit flag ${EXIT_FLAG} exists! I'm already exiting..."
-        return 0
-    fi
+    local _rc _pid _cpids _file _cmd _es_mtt_h=0 _term_timeout=5
 
-    # Creating an exit flag
-    touch ${EXIT_FLAG} || warn "Cannot create ${EXIT_FLAG}"
-
-    local _pid _cpids _file _cmd _exitcode3=0 _exitcode4=0 _term_timeout=5
+    # Saving the exit status before this hook
+    _rc=$1
 
     log "Trying to terminate sub-processes..."
     for _pid in ${child_pids}; do
@@ -246,22 +238,22 @@ hook_main_exit() {
         fi
     done
     # Removes all unexpected sub-processes
-    pkill -KILL -P ${MAINPID} &> /dev/null
+    pkill -KILL -P ${MAINPID} &> /dev/null || true
 
-    { 
+    # --- `halt`
+    if [[ boot_stage_left -eq 1 ]]; then
         debug "Looking for \`halt\` scripts..."
         # Checks for shutdown tasks in files (sequentially)
         for _file in $(ls ${DIR_NAME}/trc.sd.* ${DIR_NAME}/trc.halt.* ${DIR_NAME}/trc.d/halt.* 2>/dev/null || true); do
             (
                 set -e # Exit on errors in the sub-shell
-
+                halt_cmds_exist=1
                 ns="halt"
                 log "Running the shutdown script: ${_file}"
                 . ${_file}
             )
-            _exitcode3=$?
-            [[ ${_exitcode3} -ne 0 ]] && _exitcode4=${_exitcode3}
-            log "Exiting from the shutdown script (exitcode=${_exitcode4}): ${_file}"
+            _es_mtt_h=$?
+            log "Exiting from the shutdown script (exitcode=${_es_mtt_h}): ${_file}"
         done
 
         # Runs shutdown tasks from the command line if any
@@ -273,19 +265,18 @@ hook_main_exit() {
                 log "Running the shutdown command: ${_cmd}"
                 eval "${_cmd}"
             )
-            _exitcode3=$?
-            [[ ${_exitcode3} -ne 0 ]] && _exitcode4=${_exitcode3}
-            log "Exiting from the shutdown command (exitcode=${_exitcode4}): ${_cmd}"
+            _es_mtt_h=$?
+            log "Exiting from the shutdown command (exitcode=${_es_mtt_h}): ${_cmd}"
         done    
-    }
-
-    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
-        rm -f ${EXIT_FLAG} || { _exitcode4=$?; warn "Cannot remove ${EXIT_FLAG}"; }
-    fi
+    fi 
 
     log "Exited."
 
-    return ${_exitcode4}
+    if [[ ${halt_cmds_exist} -eq 1 ]]; then
+        exit ${_es_mtt_h}
+    else
+        exit ${_rc}
+    fi
 }
 
 hook_sub_exit() {
@@ -297,17 +288,15 @@ hook_sub_exit() {
     log "Exiting on the $(ns_long ${ns}) (exitcode=${_rc}): $@"
 
     if [[ "${RC_WAIT_POLICY}" = "wait_any" ]]; then 
-        if [[ -n "${EXIT_FLAG}" ]] && [[ ! -f ${EXIT_FLAG} ]]; then
-            # If exiting from a bg process and don't need to wait other processes, let's stop the main
-            if ps -p ${MAINPID} &> /dev/null; then
-                debug "terminating the main process <pid=${MAINPID}>"
-                kill -TERM ${MAINPID} &> /dev/null
-            fi
+        # If exiting from a bg process and don't need to wait other processes, let's stop the main
+        if ps -p ${MAINPID} &> /dev/null; then
+            debug "terminating the main process <pid=${MAINPID}>"
+            kill -TERM ${MAINPID} &> /dev/null
         fi
     fi
     # To prevent invoking error trap from error trap ;)
     # The correct exit code was taken before diving into this function
-    return 0
+    exit ${_rc}
 }
 
 infinite_loop() {
