Release new version: v1.1.1

diff --git a/docs/trc b/docs/trc
--- a/docs/trc
+++ b/docs/trc
@@ -3,7 +3,7 @@
 # TrivialRC
 # The minimalistic RC system and process manager for containers and applications
 # Copyright (c) 2016, 2017 by Oleksii Tsvietnov, me@vorakl.name
-# Version: 1.1.0
+trc_version="v1.1.1"
 
 # --[ Environment variables ]--
 # RC_DEBUG (true|false) [false]
@@ -23,162 +23,173 @@ set +e # Do not exit on errors by default
 if [[ "${RC_DEBUG}" = "true" ]]; then
     set -x # Turns on Debug mode if true
 fi
-: ${RC_WAIT_POLICY:=wait_any} # Sets default value for a wait policy
 
 main() {
-    trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_main_exit; exit ${_exitcode}' EXIT
-    trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-    trap '_exitcode=$?; [[ "${RC_WAIT_POLICY}" = "wait_err" ]] && { debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}; }' ERR
+    check_ver_usage "$1"
+
+    trap '_es_mt_ex=$?; trap '_ignore_mt_ex=1' EXIT; debug "exit-trap (exitcode=${_es_mt_ex})"; hook_main_exit ${_es_mt_ex}' EXIT
+    trap '_es_mt_s=$?; trap '_ignore_mt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=${_es_mt_s})"; exit ${_es_mt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+    trap '_es_mt_er=$?; trap '_ignore_mt_er=1' ERR; if [[ "${RC_WAIT_POLICY}" = "wait_err" ]]; then debug "err-trap (exitcode=${_es_mt_er})"; exit ${_es_mt_er}; fi' ERR
+
+    local _wait_bg_cmd _file _es_m_f=0 _es_m_d=0
 
     export SELF_NAME=$(basename $0 .sh) # Self name for logging purpose
-    export DIR_NAME=$(dirname $0)
     export MAINPID="${BASHPID}" # PID of the main process
-    export EXIT_FLAG="/tmp/trc.${MAINPID}.exiting"
-    childpid="" # Collecting child processes
-    ns="main" # Name Space
-    local _wait_bg_cmd _file _exitcode=0 _exitcode2=0
+    : ${RC_WAIT_POLICY:=wait_any}; export RC_WAIT_POLICY 
 
-    # Checks if there is an exit flag on startup
-    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
-        err "An exit flag ${EXIT_FLAG} exists! Exiting..."
-    fi
+    dir_name=$(dirname $0)
+    boot_stage_left=0
+    halt_cmds_exist=0
+    halt_cmds=()
+    child_pids="" # Collects of child processes
+    ns="main" # Name Space
 
     case "${RC_WAIT_POLICY}" in
-        wait_all)  _wait_bg_cmd="command -p wait";;
-        wait_any)  _wait_bg_cmd="command -p wait";;
-        wait_err)  _wait_bg_cmd="command -p wait";;
+        wait_all)  _wait_bg_cmd="builtin command wait";;
+        wait_any)  _wait_bg_cmd="builtin command wait";;
+        wait_err)  _wait_bg_cmd="builtin command wait";;
         *)         _wait_bg_cmd=":";;
     esac
 
     log "The wait policy: ${RC_WAIT_POLICY}"
 
-
-    # Reads commands from files to run before everything
-    set -e
-    for _file in $(ls ${DIR_NAME}/trc.boot.* ${DIR_NAME}/trc.d/boot.* 2>/dev/null || true); do
-        log "Launching on the $(ns_long ${ns}): ${_file}"
-        . ${_file}
-    done
-    set +e
-
-    # Checks for boot tasks in the command line
-    set -e
-    while [[ "$1" = "-B" ]]; do
+    if [[ "$1" = "-w" ]] || [[ "$1" = "--workdir" ]]; then
         shift
-
-        log "Launching on the $(ns_long ${ns}): $1"
-        eval "$1"
-
+        dir_name="$1"
         shift
-    done
-    set +e
+    fi
 
-    # Reads commands from files to run on the background (in parallel)
-    for _file in $(ls ${DIR_NAME}/trc.bg.* ${DIR_NAME}/trc.async.* ${DIR_NAME}/trc.d/async.* 2>/dev/null || true); do
-         {
-          (
-            set -e
-            # Run this on any exit, catching the exitcode of the "main" command,
-            # printing additional info and finishing up this sub-program with the right exitcode
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "${_file}"; exit ${_exitcode}' EXIT
-
-            # In case of exit on errors (set -e) or by a signal, catch exitcode and exit with it, which
-            # will lead to triggering an EXIT trap
-            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
-
-            ns="async"
+    debug "Looking for \`boot\` scripts and commands..."
+    {
+        # Reads commands from files to run before everything
+        set -e # On errors exits regardless of RC_WAIT_POLICY
+        for _file in $(ls ${dir_name}/trc.boot.* ${dir_name}/trc.d/boot.* 2>/dev/null || true); do
             log "Launching on the $(ns_long ${ns}): ${_file}"
             . ${_file}
-          )& 
-         } 2> /dev/null
+        done
 
-        childpid="${childpid} $!"
+        # Checks for boot tasks in the command line
+        while [[ "$1" = "-B" ]]; do
+            shift
+            log "Launching on the $(ns_long ${ns}): $1"
+            eval "$1"
+            shift
+        done
+        set +e
+    }
+    boot_stage_left=1
+
+    debug "Looking for \`halt\` commands..."
+    # Collects commands for the `halt` stage from a command line
+    while [[ "$1" = "-H" ]]; do
+        shift
+            halt_cmds_exist=1
+            halt_cmds[${#halt_cmds[*]}]="$1"
+        shift
+    done
+
+    debug "Looking for \`async\` scripts and commands..."
+    # Reads commands from files to run on the background (in parallel)
+    for _file in $(ls ${dir_name}/trc.bg.* ${dir_name}/trc.async.* ${dir_name}/trc.d/async.* 2>/dev/null || true); do
+        { # supressing stderr for avoiding uncontrolled messages like "Terminated" or "Killed"
+              (
+                # Run this on any exit, catching the exitcode of the "main" command,
+                # printing additional info and finishing up this sub-program with the right exitcode
+                trap '_es_dt_ex=$?; trap '_ignore_mt_ex=1' EXIT; debug "exit-trap (exitcode=${_es_dt_ex})"; hook_sub_exit ${_es_dt_ex} "${_file}"' EXIT
+
+                # In case of exit on errors (set -e) or by a signal, catch exitcode and exit with it, which
+                # will lead to triggering an EXIT trap
+                trap '_es_dt_s=$?; trap '_ignore_dt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_dt_s)"; exit ${_es_dt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+                trap '_es_dt_er=$?; trap '_ignore_dt_er=1' ERR; debug "err-trap (exitcode=$_es_dt_er)"; exit ${_es_dt_er}' ERR
+
+                ns="async"
+                log "Launching on the $(ns_long ${ns}): ${_file}"
+                . ${_file}
+              )& 
+        } 2> /dev/null
+        child_pids="${child_pids} $!"
     done
 
     # Checks for background tasks in the command line
     while [[ "$1" = "-D" ]]; do
         shift
         { # supressing stderr for avoiding uncontrolled messages like "Terminated" or "Killed"
-          (
-            set -e
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$1"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+              (
+                trap '_es_dt_ex=$?; trap '_ignore_dt_ex=1' EXIT; debug "exit-trap (exitcode=${_es_dt_ex})"; hook_sub_exit ${_es_dt_ex} "$1"' EXIT
+                trap '_es_dt_s=$?; trap '_ignore_dt_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_dt_s)"; exit ${_es_dt_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+                trap '_es_dt_er=$?; trap '_ignore_dt_er=1' ERR; debug "err-trap (exitcode=$_es_dt_er)"; exit ${_es_dt_er}' ERR
 
-            ns="async"
-            log "Launching on the $(ns_long ${ns}): $1"
-            eval "$1"
-          )& 
+                ns="async"
+                log "Launching on the $(ns_long ${ns}): $1"
+                eval "$1"
+              )& 
         } 2> /dev/null
-        childpid="${childpid} $!"
+        child_pids="${child_pids} $!"
         shift
     done
 
-   # Checks for foreground tasks in files (sequentially)
-    for _file in $(ls ${DIR_NAME}/trc.fg.* ${DIR_NAME}/trc.sync.* ${DIR_NAME}/trc.d/sync.* 2>/dev/null || true); do
+    debug "Looking for \`sync\` scripts and commands..." 
+    # Checks for foreground tasks in files (sequentially)
+    for _file in $(ls ${dir_name}/trc.fg.* ${dir_name}/trc.sync.* ${dir_name}/trc.d/sync.* 2>/dev/null || true); do
         (
-            set -e
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "${_file}"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+            trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "${_file}"; exit ${_es_ft_ex}' EXIT
+            trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_es_ft_er=$?; trap '_ignore_ft_er=1' ERR; debug "err-trap (exitcode=$_es_ft_er)"; exit ${_es_ft_er}' ERR
 
             ns="sync"
             log "Launching on the $(ns_long ${ns}): ${_file}"
             . ${_file}
         )
         # Catch the exitcode of a foreground sub-program
-        _exitcode=$?
+        _es_m_f=$?
     done
 
     # Checks for foreground tasks in the command line
     while [[ "$1" = "-F" ]]; do
         shift
-        set +e
         (
-            set -e
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$1"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=${_exitcode})"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=${_exitcode})"; exit ${_exitcode}' ERR
+            trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "$1"; exit ${_es_ft_ex}' EXIT
+            trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_es_ft_er=$?; trap '_ignore_ft_er=1' ERR; debug "err-trap (exitcode=$_es_ft_er)"; exit ${_es_ft_er}' ERR
 
             ns="sync"
             log "Launching on the $(ns_long ${ns}): $1"
             eval "$1"
         )
-        _exitcode=$?
+        _es_m_f=$?
         shift
     done
 
-     # Checks for a foreground task in the command line (one parameter with all commands)
+    # Checks for a foreground task in the command line (one parameter with all commands)
     if [[ -n "$*" ]]; then
         (
             set -e
-            trap '_exitcode=$?; debug "exit-trap (exitcode=${_exitcode})"; hook_sub_exit ${_exitcode} "$@"; exit ${_exitcode}' EXIT
-            trap '_exitcode=$?; debug "sig-trap (exitcode=$_exitcode)"; exit ${_exitcode}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
-            trap '_exitcode=$?; debug "err-trap (exitcode=$_exitcode)"; exit ${_exitcode}' ERR
+            trap '_es_ft_ex=$?; trap '_ignore_ft_ex=1' EXIT; debug "exit-trap (exitcode=${_es_ft_ex})"; hook_sub_exit ${_es_ft_ex} "$@"; exit ${_es_ft_ex}' EXIT
+            trap '_es_ft_s=$?; trap '_ignore_ft_s=1' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS; debug "sig-trap (exitcode=$_es_ft_s)"; exit ${_es_ft_s}' HUP INT ILL TRAP ABRT BUS FPE USR1 SEGV USR2 PIPE ALRM TERM XCPU XFSZ VTALRM SYS
+            trap '_es_ft_er=$?; trap '_ignore_ft_er=1' ERR; debug "err-trap (exitcode=$_es_ft_er)"; exit ${_es_ft_er}' ERR
 
             ns="sync"
             log "Launching on the $(ns_long ${ns}): $@"
             "$@"
         )
         # Catch the exitcode of a foreground sub-program
-        _exitcode=$?
+        _es_m_f=$?
     fi
 
     # Wait for all background processes and exit with a status of the last one
     # or with 128+SIGNAL in case of getting a signal
-    ${_wait_bg_cmd} ${childpid}
-    _exitcode2=$?
+    # this is a work around for not trigerring ERR trap in main() two times in case of non 0 exist status
+    ${_wait_bg_cmd} ${child_pids} || _es_m_d=$?
 
-    if [ ${_exitcode2} -ne 0 ]; then
-        _exitcode=${_exitcode2} # update exit code only if one of background processes has failed
+    if [ ${_es_m_d} -ne 0 ]; then
+        _es_m_f=${_es_m_d} # update exit code only if one of background processes has failed
     fi
 
     if [[ "${RC_WAIT_POLICY}" = "wait_forever" ]]; then
         infinite_loop
     fi
 
-    return ${_exitcode}
+    return ${_es_m_f}
 }
 
 say() {
@@ -207,33 +218,13 @@ debug() {
 }
 
 hook_main_exit() {
-    set +e # do not stop or errors anyway
+    local _rc _pid _cpids _file _cmd _es_mtt_h=0 _term_timeout=5
 
-    # Checks if there is an exit flag on exit
-    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
-        warn "An exit flag ${EXIT_FLAG} exists! I'm already exiting..."
-        return 0
-    fi
+    # Saving the exit status before this hook
+    _rc=$1
 
-    # Creating an exit flag
-    touch ${EXIT_FLAG} || warn "Cannot create ${EXIT_FLAG}"
-
-    local _pid _cpids _file _term_timeout
-    _term_timeout=5
-
-    log "Going down. Running shutdown scripts..."
-    # Checks for shutdown tasks in files (sequentially)
-    for _file in $(ls ${DIR_NAME}/trc.sd.* ${DIR_NAME}/trc.halt.* ${DIR_NAME}/trc.d/halt.* 2>/dev/null || true); do
-        (
-            ns="halt"
-            set -e # Exit on errors in the sub-shell
-            log "Running the shutdown script: ${_file}"
-            . ${_file}
-        )
-    done
-
-    log "Handling of termination..."
-    for _pid in ${childpid}; do
+    log "Trying to terminate sub-processes..."
+    for _pid in ${child_pids}; do
         if ps -p ${_pid} &> /dev/null; then
             debug "terminating the child process <pid=${_pid}>"
 
@@ -253,16 +244,45 @@ hook_main_exit() {
         fi
     done
     # Removes all unexpected sub-processes
-    pkill -KILL -P ${MAINPID} &> /dev/null
+    pkill -KILL -P ${MAINPID} &> /dev/null || true
 
-    if [[ -n "${EXIT_FLAG}" ]] && [[ -f ${EXIT_FLAG} ]]; then
-        rm -f ${EXIT_FLAG} || warn "Cannot remove ${EXIT_FLAG}"
-    fi
+    # --- `halt`
+    if [[ boot_stage_left -eq 1 ]]; then
+        debug "Looking for \`halt\` scripts..."
+        # Checks for shutdown tasks in files (sequentially)
+        for _file in $(ls ${dir_name}/trc.sd.* ${dir_name}/trc.halt.* ${dir_name}/trc.d/halt.* 2>/dev/null || true); do
+            (
+                set -e # Exit on errors in the sub-shell
+                halt_cmds_exist=1
+                ns="halt"
+                log "Running the shutdown script: ${_file}"
+                . ${_file}
+            )
+            _es_mtt_h=$?
+            log "Exiting from the shutdown script (exitcode=${_es_mtt_h}): ${_file}"
+        done
+
+        # Runs shutdown tasks from the command line if any
+        for _cmd in "${halt_cmds[@]}"; do
+            (
+                set -e # Exit on errors in the sub-shell
+
+                ns="halt"
+                log "Running the shutdown command: ${_cmd}"
+                eval "${_cmd}"
+            )
+            _es_mtt_h=$?
+            log "Exiting from the shutdown command (exitcode=${_es_mtt_h}): ${_cmd}"
+        done    
+    fi 
 
     log "Exited."
 
-    # It's not needed to exit with a proper exit code here.
-    # The programm will exit with correct exit code from EXIT trap of main()
+    if [[ ${halt_cmds_exist} -eq 1 ]]; then
+        exit ${_es_mtt_h}
+    else
+        exit ${_rc}
+    fi
 }
 
 hook_sub_exit() {
@@ -274,17 +294,15 @@ hook_sub_exit() {
     log "Exiting on the $(ns_long ${ns}) (exitcode=${_rc}): $@"
 
     if [[ "${RC_WAIT_POLICY}" = "wait_any" ]]; then 
-        if [[ -n "${EXIT_FLAG}" ]] && [[ ! -f ${EXIT_FLAG} ]]; then
-            # If exiting from a bg process and don't need to wait other processes, let's stop the main
-            if ps -p ${MAINPID} &> /dev/null; then
-                debug "terminating the main process <pid=${MAINPID}>"
-                kill -TERM ${MAINPID} &> /dev/null
-            fi
+        # If exiting from a bg process and don't need to wait other processes, let's stop the main
+        if ps -p ${MAINPID} &> /dev/null; then
+            debug "terminating the main process <pid=${MAINPID}>"
+            kill -TERM ${MAINPID} &> /dev/null
         fi
     fi
     # To prevent invoking error trap from error trap ;)
     # The correct exit code was taken before diving into this function
-    return 0
+    exit ${_rc}
 }
 
 infinite_loop() {
@@ -306,6 +324,30 @@ ns_long() {
     esac
 
     echo "${_ns}"
+}
+
+check_ver_usage() {
+    case "$1" in
+        -v|--version) print_version ;;
+        -h|--help)    print_usage ;;
+         *)           : ;;
+    esac
+}
+
+print_usage() {
+    local _self=$0
+    echo "Usage: ${_self} [-w|--workdir 'dir'] [-B 'cmds' [...]] [-H 'cmds' [...]] [-D 'cmds' [...]] [-F 'cmds' [...]] [cmd [args]]"
+    echo "Examples:"
+    echo -e " $ ${_self} -B 'name=\$(id -un); echo booting...' -H 'echo halting...' -F 'echo Hello, \${name}!'"
+    echo -e " $ RC_WAIT_POLICY=wait_all ${_self} -D 'echo Hello' -D 'sleep 2; echo World' echo waiting..."
+    echo -e " $ RC_VERBOSE=true ${_self} -F 'echo -n \"Hello \"; echo World'"
+    echo -e " $ ${_self} --workdir /opt/app"
+    exit 0
+}
+
+print_version() {
+    echo "$trc_version"
+    exit 0
 }
 
 main "$@"
